name: CI

on:
  push:
    branches:
      - testing

jobs:
  build_with_signing:
    runs-on: macos-latest

    steps:
    - name: check Xcode version
      run: /usr/bin/xcodebuild -version
      
    - name: Checkout repository
      uses: actions/checkout@v2
   
    - name: Install the Apple certificate and provisioning profile
      env: 
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROFILE_PROVISION_64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.EAP_KEYCHAIN_PASSWORD }}
          TEAM_ID: ${{ secrets.TEAM_ID}}
      run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles   
    # - name: clean build 
    #   run: |
    #       cd SmartWeights
    #       xcodebuild -scheme "SmartWeights" \
    #       -sdk iphonesimulator \
    #       -configuration Debug \
    #       -destination generic/platform=iOS \
    #       clean build
    - name: Clean
      run: |
        cd SmartWeights
        xcodebuild clean -scheme SmartWeights -workspace SmartWeights.xcodeproj/project.xcworkspace
    - name: iOS Build Action
  # You may pin to the exact commit or the version.
  # uses: yukiarrr/ios-build-action@0150a4152ca4f11ce16f122c24ce0c15dfbaa45f
      uses: yukiarrr/ios-build-action@v1.11.2
      with:
        # Base64 encoded p12 key
        # p12-key-base64: # optional
        # Base64 encoded certificate for the p12 key
        # p12-cer-base64: # optional
        # Base64 encoded p12 file (key + cert)
        # p12-base64: # optional
        # Base64 encoded mobileprovision file
        # mobileprovision-base64: # optional
        # p12 key path
        # p12-key-path: # optional
        # Certificate path for the p12 key
        # p12-cer-path: # optional
        # p12 path (key + cert)
        # p12-path: # optional
        # mobileprovision path
        # mobileprovision-path: # optional
        # Project path
        project-path: SmartWeights
        # For example, iOS Distribution
        code-signing-identity: iOS Distribution
        # Team id
        team-id: $TEAM_ID
        # Workspace path
        # workspace-path: # optional, default is 
        # Choose app-store, ad-hoc, package, enterprise, development, or developer-id
        # export-method: # optional, default is app-store
        # For example, Debug, Release
        # configuration: # optional, default is Release
        # Certificate password
        # certificate-password: # optional, default is 
        # Output path of ipa
        # output-path: # optional, default is output.ipa
        # Scheme
        scheme: SmartWeights
        # Targets to be updated with mobileprovision, code signing identity, etc
        # update-targets: # optional, default is 
        # Deprecated, use update-targets instead
        # disable-targets: # optional, default is 
        # Path to an export options plist
        # export-options: # optional, default is 
        # The SDK that should be used for building the application
        # build-sdk: # optional, default is 
        # Use a custom destination for building the app
        # build-destination: # optional, default is 
        # Path for Swift Package Manager dependencies
        # cloned-source-packages-path: # optional, default is 
        # Path to your entitlements file
        # entitlements-file-path: # optional, default is 
        # Increment the build number before building the application
        # increment-build-number: # optional, default is 
        # Increment the version number of your project. Supports patch, minor, major or a specific version number.
        # increment-version-number: # optional, default is 
        # Bundle identifier of the application.
        # bundle-identifier: # optional, default is 
        # App Store Connect API Key ID
        # app-store-connect-api-key-id: # optional, default is 
        # App Store Connect API Key Issuer ID
        # app-store-connect-api-key-issuer-id: # optional, default is 
        # Base64 encoded App Store Connect API Key
        # app-store-connect-api-key-base64: # optional, default is 
        # Build path
        # build-path: # optional, default is 
        # Custom Keychain Name
        # custom-keychain-name: # optional, default is ios-build.keychain
              
    # - name: Build
    #   run: |
    #     cd SmartWeights
    #     xcodebuild build -scheme SmartWeights -workspace SmartWeights.xcodeproj/project.xcworkspace 
    #     -username ${{ secrets.APPLE_ID_EMAIL }}
    #     -password ${{ secrets.APPLE_ID_PASSWORD }}
    # - name: Test
    #   run: xcodebuild test -scheme SmartWeights -workspace SmartWeights.xcodeproj/project.xcworkspace
    
