name: iOS CI/CD with TestFlight

on:
  push:
    branches: ["development"]

jobs:
  build_and_deploy:
    name: Build, Test, and Deploy to TestFlight
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup CocoaPods
        run: |
          gem install bundler
          bundle install
          bundle exec pod install

      - name: Build and Test
        run: xcodebuild -workspace SmartWeights.xcworkspace -scheme SmartWeights -destination "platform=iOS Simulator,name=iPhone 12" clean build test

      - name: Archive
        run: xcodebuild -workspace SmartWeights.xcworkspace -scheme SmartWeights -destination generic/platform=iOS archive -archivePath build/SmartWeights.xcarchive

      # - name: Upload to App Store Connect
      #   uses: apple/actions/upload-build-artifact@v1
      #   with:
      #     api_key_path: ${{secrets.APP_STORE_CONNECT_API_KEY}}
      #     issuer_id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
      #     key_id: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
      #     app_id: ${{ secrets.APP_STORE_CONNECT_APP_ID }}
      #     ipa_path: build/SmartWeights.xcarchive/Products/Applications/SmartWeights.ipa

     
      - name: Export IPA
        run: |
          xcodebuild -exportArchive -archivePath "build/SmartWeights.xcarchive" -exportOptionsPlist ExportOptions.plist -exportPath build

      - name: Upload to TestFlight
        run: |
          xcrun altool --upload-app -f build/*.ipa -t ios -u ${{ secrets.APPLE_ID_EMAIL }} -p ${{ secrets.APPLE_ID_PASSWORD }}
        # - name: Upload to TestFlight
        #   uses: apple/actions/upload-build-artifact@v1
        #   with:
        #     path: build/*.ipa
        #     transporter-mode: distribute
        #     api_key_path: ${{secrets.APP_STORE_CONNECT_API_KEY}}
        #     issuer_id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        #     key_id: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
        #     app_id: ${{ secrets.APP_STORE_CONNECT_APP_ID }}
        #     groups: 'Internal Testers'
        #     ipa_path: build/SmartWeights.xcarchive/Products/Applications/SmartWeights.ipa
